#!/bin/sh
# SPDX-License-Identifier: MIT

set -e

QCMD=$(tools/gen_qemu_cmd.sh -X "-cdrom /tmp/bootable-davix.iso" -X "-serial stdio" -X "-nic none" $@)

make # build the kernel (and davix-multiboot2)

if [ -d /tmp/isodir.davix ]; then
	rm -r /tmp/isodir.davix
fi

mkdir -p /tmp/isodir.davix/boot/grub

cp build/davix-multiboot2 /tmp/isodir.davix/davix-multiboot2
cat << EOF >> /tmp/isodir.davix/boot/grub/grub.cfg

insmod fat
insmod efi_gop

set default=0
set timeout=1

menuentry "Davix" {
	echo "Loading multiboot2 image..."
	multiboot2 /davix-multiboot2
	echo "Booting..."
	boot
}

EOF
grub-mkrescue -o /tmp/bootable-davix.iso /tmp/isodir.davix 2>/dev/null
$QCMD | tools/format_serial.sh
