# Subdirectory Makefile.
# Copyright (C) 2024  dbstream

kobjs += cpu/
kobjs += acpi.o
kobjs += apic.o
kobjs += exception.o
kobjs += exec.o
kobjs += header.o
kobjs += hpet.o
kobjs += idt_entry.o
kobjs += idt.o
kobjs += ipi.o
kobjs += irq.o
kobjs += nmi.o
kobjs += printk_0xe9.o
kobjs += setup.o
kobjs += smp.o
kobjs += startup64.o
kobjs += syscall_entry.o
kobjs += syscall.o
kobjs += task_switch.o
kobjs += task.o
kobjs += time.o
kobjs += tsc.o
