# Subdirectory Makefile.
# Copyright (C) 2024  dbstream

kobjs += sched/
kobjs += context.o
kobjs += main.o
kobjs += panic.o
kobjs += printk.o
kobjs += smp.o
kobjs += task_creation.o

FLAGS-main.o := "-DKERNELVERSION=\"$(KERNELVERSION)\""
