# SPDX-License-Identifier: MIT

obj-y += sched/built-in.a
obj-y += avltree.c.o
obj-y += ctype.c.o
obj-y += panic.c.o
obj-y += printk_lib.c.o
obj-y += printk.c.o
obj-y += resource.c.o
obj-y += setup.c.o
obj-y += stdlib.c.o
