# Subdirectory Makefile.
# Copyright (C) 2025-present  dbstream

kobjs += file.o
kobjs += fs_context.o
kobjs += inode.o
kobjs += lookup.o
kobjs += mount.o
kobjs += open.o
kobjs += tmpfs.o
kobjs += vnode.o
