# Subdirectory Makefile.
# Copyright (C) 2024-present  dbstream

kobjs += initmem.o
kobjs += kmalloc.o
kobjs += mmap.o
kobjs += pfn_slab.o
kobjs += pgalloc.o
kobjs += process_mm.o
kobjs += vm.o
kobjs += vmap.o
