# Makefile for uACPI integration into Davix.
# Copyright (C) 2025  dbstream
#
# This file, uacpi/GNUmakefile, and uacpi/README.davix are NOT part of uACPI.

kobjs += default_handlers.o
kobjs += event.o
kobjs += interpreter.o
kobjs += io.o
kobjs += mutex.o
kobjs += namespace.o
kobjs += notify.o
kobjs += opcodes.o
kobjs += opregion.o
kobjs += osi.o
kobjs += registers.o
kobjs += resources.o
kobjs += shareable.o
kobjs += sleep.o
kobjs += stdlib.o
kobjs += tables.o
kobjs += types.o
kobjs += uacpi.o
kobjs += utilities.o
