#!/bin/sh
# SPDX-License-Identifier: MIT
DIRS="acpi doc include kernel mm tools"
if [ "$ARCH" != "" ]; then
	DIRS="$DIRS arch/$ARCH"
else
	DIRS="$DIRS arch"
fi

FILES="$(find $DIRS -type f)"

FILES="$FILES $(find . -maxdepth 1 -type f -not -name .\*)"

exec grep --color=auto -Hn "$@" $FILES
